//! Built-in connector registry (E1.4).

use super::types::{
    ConnectorDescriptor, ConnectorKind, DeliveryContract, SupportLevel,
};

/// All first-party and planned connectors known to the lean binary / matrix.
#[must_use]
pub fn builtins() -> &'static [ConnectorDescriptor] {
    &BUILTINS
}

/// Look up a connector by stable id.
#[must_use]
pub fn builtin(id: &str) -> Option<&'static ConnectorDescriptor> {
    builtins().iter().find(|connector| connector.id == id)
}

/// Markdown body for `docs/connectors/support-matrix.md` (without the title).
///
/// Kept in code so the published matrix cannot drift from the registry.
#[must_use]
pub fn matrix_markdown() -> String {
    let mut out = String::from(
        "<!-- Generated by pramen_core::connector::matrix_markdown — do not edit rows by hand; update the registry. -->\n\
         \n\
         Support levels: **supported** (first-party, CI-backed), **preview** (shipped with\n\
         documented limits), **planned** (named, not in the default binary).\n\
         \n\
         | Id | Kind | Level | Modes / schemes | Delivery | Notes |\n\
         | --- | --- | --- | --- | --- | --- |\n",
    );
    for connector in builtins() {
        let modes_schemes = match connector.kind {
            ConnectorKind::Sink if !connector.modes.is_empty() => connector.modes.join(", "),
            ConnectorKind::Source if !connector.schemes.is_empty() => {
                connector.schemes.join(", ")
            }
            _ => "—".to_owned(),
        };
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {} |\n",
            connector.id,
            connector.kind.as_str(),
            connector.support_level.as_str(),
            modes_schemes,
            connector.delivery.summary(),
            connector.notes,
        ));
    }
    out.push('\n');
    out
}

static BUILTINS: [ConnectorDescriptor; 8] = [
    ConnectorDescriptor {
        id: "source.objectStore",
        kind: ConnectorKind::Source,
        support_level: SupportLevel::Supported,
        summary: "Parquet or NDJSON from local paths, file://, or s3://",
        modes: &[],
        schemes: &["file", "s3"],
        delivery: DeliveryContract::SourceCheckpointAtLeastOnce,
        notes: "Optional Azure/GCS in Phase 2; residency schemes validated when configured",
    },
    ConnectorDescriptor {
        id: "sink.postgres",
        kind: ConnectorKind::Sink,
        support_level: SupportLevel::Supported,
        summary: "Native binary COPY into PostgreSQL (append or upsert)",
        modes: &["append", "upsert"],
        schemes: &[],
        delivery: DeliveryContract::CommitBarrierAtLeastOnce,
        notes: "DSN from env (default PRAMEN_POSTGRES_DSN); secrets never in the spec",
    },
    ConnectorDescriptor {
        id: "sink.flightSql",
        kind: ConnectorKind::Sink,
        support_level: SupportLevel::Preview,
        summary: "Append Arrow batches via Flight SQL CommandStatementIngest",
        modes: &["append"],
        schemes: &[],
        delivery: DeliveryContract::CommitBarrierAtLeastOnce,
        notes: "Upsert rejected at validate; optional Bearer from PRAMEN_FLIGHT_SQL_TOKEN (ADR 0008)",
    },
    ConnectorDescriptor {
        id: "sink.adbc",
        kind: ConnectorKind::Sink,
        support_level: SupportLevel::Planned,
        summary: "ADBC-backed warehouse sinks (separate distribution profile)",
        modes: &["append"],
        schemes: &[],
        delivery: DeliveryContract::CommitBarrierAtLeastOnce,
        notes: "E1.1; first warehouse chosen by demand (ADR); not in the lean binary",
    },
    ConnectorDescriptor {
        id: "transform.sql",
        kind: ConnectorKind::Transform,
        support_level: SupportLevel::Supported,
        summary: "Per-batch DataFusion SQL over table `input`",
        modes: &[],
        schemes: &[],
        delivery: DeliveryContract::InProcess,
        notes: "Deterministic; no network",
    },
    ConnectorDescriptor {
        id: "transform.wasm",
        kind: ConnectorKind::Transform,
        support_level: SupportLevel::Supported,
        summary: "WASM component transforms (WIT / Arrow IPC)",
        modes: &[],
        schemes: &[],
        delivery: DeliveryContract::InProcess,
        notes: "Fuel/memory/deadline limits; `pramen transform test` conformance",
    },
    ConnectorDescriptor {
        id: "transform.ai",
        kind: ConnectorKind::Transform,
        support_level: SupportLevel::Supported,
        summary: "Schema-bound ai.extract / ai.classify / ai.generate",
        modes: &[],
        schemes: &[],
        delivery: DeliveryContract::LedgerBackedSemantic,
        notes: "Budgets and onInvalid policies; providers: mock, openai-compat, bedrock",
    },
    ConnectorDescriptor {
        id: "transform.ai.batch",
        kind: ConnectorKind::Transform,
        support_level: SupportLevel::Supported,
        summary: "Provider-batch execution path for semantic transforms",
        modes: &[],
        schemes: &[],
        delivery: DeliveryContract::LedgerBackedSemantic,
        notes: "Job ids recorded before await; crash reconcile without re-billing",
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtins_include_core_sinks_and_source() {
        let ids: Vec<&str> = builtins().iter().map(|c| c.id).collect();
        assert!(ids.contains(&"sink.postgres"));
        assert!(ids.contains(&"sink.flightSql"));
        assert!(ids.contains(&"source.objectStore"));
        assert!(ids.contains(&"sink.adbc"));
        assert_eq!(builtin("sink.flightSql").unwrap().support_level, SupportLevel::Preview);
        assert_eq!(builtin("sink.adbc").unwrap().support_level, SupportLevel::Planned);
        assert!(builtin("nope").is_none());
    }

    #[test]
    fn ids_are_unique() {
        let mut seen = std::collections::BTreeSet::new();
        for connector in builtins() {
            assert!(seen.insert(connector.id), "duplicate id {}", connector.id);
        }
    }

    #[test]
    fn matrix_markdown_lists_every_builtin() {
        let md = matrix_markdown();
        for connector in builtins() {
            assert!(
                md.contains(&format!("`{}`", connector.id)),
                "matrix missing {}",
                connector.id
            );
        }
    }

    #[test]
    fn committed_matrix_artifact_is_current() {
        let committed = include_str!("../../../../docs/connectors/support-matrix.md");
        let expected = format!("# Connector support matrix\n\n{}", matrix_markdown());
        assert_eq!(
            committed, expected,
            "docs/connectors/support-matrix.md is stale; regenerate with \
             `cargo run -p pramen-core --example generate_connector_matrix --quiet \
              > docs/connectors/support-matrix.md`"
        );
    }
}
