#!/usr/bin/env bash
# Regenerate or check the competitive scoreboard (docs/benchmarks/compare-scoreboard.*).
#
#   ./scripts/compare-scoreboard.sh           # refresh JSON (RQ2 rows) + Markdown
#   ./scripts/compare-scoreboard.sh --check   # fail if committed artifacts are stale
#
# Optional (not CI):
#   COMPARE_LIVE_BENCH=1  → print how to refresh pg-load-path from bench.sh
#   COMPARE_REDPANDA=1 / COMPARE_DOCETL=1 → point at competitor harness READMEs
set -euo pipefail
cd "$(dirname "$0")/.."

JSON=docs/benchmarks/compare-scoreboard.json
MD=docs/benchmarks/compare-scoreboard.md
RQ2=docs/research/rq2-memoization-metrics.json
CHECK=0
if [ "${1:-}" = "--check" ]; then
  CHECK=1
fi

if [ ! -f "$JSON" ]; then
  echo "error: missing $JSON" >&2
  exit 1
fi

chmod +x scripts/compare-scoreboard.sh 2>/dev/null || true

python3 - "$JSON" "$MD" "$RQ2" "$CHECK" <<'PY'
import json, sys, datetime, pathlib

json_path, md_path, rq2_path, check_flag = sys.argv[1:5]
check = check_flag == "1"

def refresh(data: dict, rq2_path: str) -> dict:
    rq2_file = pathlib.Path(rq2_path)
    if not rq2_file.is_file():
        return data
    rq2 = json.loads(rq2_file.read_text(encoding="utf-8"))
    by_id = {s["id"]: s for s in rq2.get("scenarios", [])}
    for scenario in data["scenarios"]:
        if scenario["id"] != "memoization-reuse":
            continue
        rows = []
        online = by_id.get("crash_replay_online")
        if online is not None:
            rows.append({
                "system": "Pramen ledger replay (online)",
                "metric": "reuse_pct",
                "value": str(int(online.get("reusePct", 0))),
                "detail": (
                    f"{online.get('providerCalls', 0)} provider calls / "
                    f"{online.get('tokensBilled', 0)} tokens on replay"
                ),
            })
        batch = by_id.get("crash_reconcile_batch")
        if batch is not None:
            detail = batch.get("detail") or {}
            rows.append({
                "system": "Pramen batch crash reconcile",
                "metric": "rebill_calls",
                "value": str(detail.get("rebillCalls", 0)),
                "detail": (
                    f"{detail.get('rowsRecovered', '?')}/"
                    f"{batch.get('recordsSeen', '?')} rows recovered without re-submit billing"
                ),
            })
        dup = by_id.get("duplicate_heavy") or by_id.get("duplicate-heavy")
        if dup is not None:
            savings = dup.get("savingsPct", dup.get("reusePct"))
            rows.append({
                "system": "Pramen duplicate-heavy (200/20 unique)",
                "metric": "savings_pct_vs_naive",
                "value": str(int(savings)) if savings is not None else "n/a",
                "detail": "vs per-row dispatch with no ledger",
            })
        if rows:
            scenario["rows"] = rows
            scenario["status"] = "measured"
            scenario["report"] = "docs/research/rq2-memoization.md"
            scenario["metricsRef"] = "docs/research/rq2-memoization-metrics.json"
    return data

def render(data: dict) -> str:
    lines = [
        "<!-- Generated by scripts/compare-scoreboard.sh — do not edit by hand. -->",
        "# Competitive scoreboard",
        "",
        f"Generated: `{data['generatedAt']}`",
        "",
        "## Update policy",
        "",
        f"- **Offline:** {data['policy']['offline']}",
        f"- **Cloud / competitor AI:** {data['policy']['cloud']}",
        "",
        "Primary sources:",
        "",
        "- [`docs/benchmarks/2026-07-12-v1.md`](2026-07-12-v1.md)",
        "- [`docs/spikes/s1-3-postgres-copy.md`](../spikes/s1-3-postgres-copy.md)",
        "- [`docs/research/rq2-memoization-metrics.json`](../research/rq2-memoization-metrics.json)",
        "",
        "Orientation (when to choose what): [`docs/compare/orientation.md`](../compare/orientation.md).",
        "",
    ]
    for scenario in data["scenarios"]:
        lines.append(f"## {scenario['title']} (`{scenario['id']}`)")
        lines.append("")
        lines.append(f"**Status:** `{scenario['status']}`")
        report = scenario.get("report")
        if report:
            if report.startswith("docs/benchmarks/"):
                link = report.removeprefix("docs/benchmarks/")
            elif report.startswith("docs/"):
                link = "../" + report.removeprefix("docs/")
            else:
                link = report
            lines.append(f"**Report:** [`{report}`]({link})")
        if scenario.get("harness"):
            lines.append(f"**Harness:** `{scenario['harness']}`")
        if scenario.get("notes"):
            lines.append("")
            lines.append(scenario["notes"])
        lines.append("")
        rows = scenario.get("rows") or []
        if not rows:
            lines.append("_No measured rows yet._")
            lines.append("")
            continue
        lines.append("| System | Metric | Value | Detail |")
        lines.append("| --- | --- | --- | --- |")
        for row in rows:
            lines.append(
                f"| {row['system']} | `{row['metric']}` | {row['value']} | {row['detail']} |"
            )
        lines.append("")
    return "\n".join(lines) + "\n"

raw = json.loads(pathlib.Path(json_path).read_text(encoding="utf-8"))
updated = refresh(raw, rq2_path)
updated["generatedAt"] = datetime.datetime.now(datetime.timezone.utc).strftime(
    "%Y-%m-%dT%H:%M:%SZ"
)
new_json = json.dumps(updated, indent=2) + "\n"
new_md = render(updated)

if check:
    # Stale if refreshing RQ2 rows or re-rendering MD would change committed files
    # (ignore generatedAt-only drift on JSON by comparing scenarios).
    committed = json.loads(pathlib.Path(json_path).read_text(encoding="utf-8"))
    committed_md = (
        pathlib.Path(md_path).read_text(encoding="utf-8")
        if pathlib.Path(md_path).is_file()
        else ""
    )
    expected = refresh(json.loads(pathlib.Path(json_path).read_text(encoding="utf-8")), rq2_path)
    # Keep committed timestamp so MD compare is stable when only clock would change
    expected["generatedAt"] = committed.get("generatedAt", expected["generatedAt"])
    expected_md = render(expected)
    scenarios_drift = expected.get("scenarios") != committed.get("scenarios")
    md_drift = committed_md != expected_md
    if scenarios_drift or md_drift:
        print(
            "error: compare-scoreboard is stale; run: mise run compare-scoreboard",
            file=sys.stderr,
        )
        sys.exit(1)
    print("compare-scoreboard: ok")
    sys.exit(0)

pathlib.Path(json_path).write_text(new_json, encoding="utf-8")
pathlib.Path(md_path).write_text(new_md, encoding="utf-8")
print(f"wrote {json_path}")
print(f"wrote {md_path}")
PY

if [ "${COMPARE_LIVE_BENCH:-}" = "1" ]; then
  echo ""
  echo "COMPARE_LIVE_BENCH=1: refresh pg-load-path from a live suite:"
  echo "  mise run bench-e2e"
  echo "Then update docs/benchmarks/compare-scoreboard.json with new ranges +"
  echo "machine notes, and re-run: mise run compare-scoreboard"
fi
if [ "${COMPARE_REDPANDA:-}" = "1" ]; then
  echo "COMPARE_REDPANDA=1: see compare/redpanda-connect/README.md"
fi
if [ "${COMPARE_DOCETL:-}" = "1" ]; then
  echo "COMPARE_DOCETL=1: see compare/docetl/README.md"
fi
